### ISSUE TITLE
parameters are not allowed on the `/authorize` endpoint

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-javascript-samples#1]
(AUTH-3833)
I've receiving this warning while logging in using samples.
![image](https://cloud.githubusercontent.com/assets/1114365/23619701/287ea9c2-029d-11e7-9f23-f771ffc179b9.png)

**Comment by luisrudge** [comment]
this is due to an outdated dependency. it's fixed now

**Comment by aaroncolaco** [comment]
@luisrudge, I still get this warning. I'm using lock version 11.0.1

What could be the problem? Do I need to update some dependencies manually?

**Comment by benjaminleetmaa** [comment]
Me too

**Comment by markwaddle** [comment]
i'm still experiencing this problem with 11.0.1 as well.

what dependency did you update @luisrudge ?

**Comment by markwaddle** [comment]
after investigating the linked issue, i realize that this issue is not an actual problem for me. it's a warning in auth0-lock.

**Comment by SteveALee** [comment]
Just got this myself
